# our base image
FROM maven:3-jdk-8-slim AS builder
COPY src /home/app/src
COPY pom.xml /home/app
RUN mvn -f /home/app/pom.xml clean package

FROM openjdk:17-alpine

COPY --from=builder home/app/target/hexagonal-architecture-1.0.0-SNAPSHOT.jar /usr/local/lib/app.jar
EXPOSE 9393
ENTRYPOINT [ "java", "-jar", "usr/local/lib/app.jar" ]






