version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:11
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5431:5432"
    restart: unless-stopped
  app:
    image: lordstabbopriceapp:1.0
    build:
      context: .
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "9393:9393"
