CREATE
  TABLE IF NOT EXISTS PRICES(
    BRAND_ID INT PRIMARY KEY,
    START_DATE DATE,
    END_DATE DATE,
    PRICE_LIST DOUBLE NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PRIORITY INT NOT NULL,
    PRICE_LIST DOUBLE NOT NULL,
    CURRENCY VARCHAR(7)
  );

